### ISSUE TITLE
Shuffle function not random at all

### ISSUE THREAD

**Issue by buehlert** [FMNSSun/plusspector#2]
## Important code parts.

Packet generation: https://github.com/FMNSSun/plusspector/blob/36b19ad97e1e662627c81ef4c0d3386ed57b936b/pluspector.go#L201-L209

Shuffle: https://github.com/FMNSSun/plusspector/blob/36b19ad97e1e662627c81ef4c0d3386ed57b936b/pluspector.go#L192-L199

In dropRate function, you generate the payload once and then shuffle in each loop iteration: https://github.com/FMNSSun/plusspector/blob/36b19ad97e1e662627c81ef4c0d3386ed57b936b/pluspector.go#L343-L346

## Shuffle not random

Let's see what the shuffle function produces.

### For i > 0
```
First iteration:
data[i-1] = data[i] ^ data[i-1] ^ i = v[i] ^ 3B ^ v[i-1] ^ 3B ^ i
Replacing v with value from genData: data[i-1] = 2D ^ i ^ 3B ^ 2D ^ i-1 ^ 3B ^ i = i-1

Following iterations:
data[i-1] = data[i] ^ data[i-1] ^ i = v[i] ^ 3B ^ v[i-1] ^ 3B ^ i
Now v[i] = i: data[i-1] = i ^ 3B ^ i-1 ^ 3B ^ i = i-1

=> data[i-1] is always i-1
```

### For i = 0
```
First iteration:
data[0] = data[1] ^ data[0] ^ 1 = v[1] ^ 3B ^ v[0] ^ 1        # data[0] has no 3B!
Replacing v with value from genData: data[i-1] = 2D ^ 1 ^ 3B ^ 2D ^ 0 ^ 1 = 3B

Second iteration:
data[0] = data[1] ^ data[0] ^ 1 = v[1] ^ 3B ^ v[0] ^ i
Replacing v[1] with 1 and v[0] with 3B: data[i-1] = 1 ^ 3B ^ 3B ^ 1 = 0

Third iteration:
data[0] = data[1] ^ data[0] ^ 1 = v[1] ^ 3B ^ v[0] ^ i
Replacing v[1] with 1 and v[0] with 0: data[i-1] = 1 ^ 3B ^ 0 ^ 1 = 3B

=> data[0] is oscillating between 3B and 0
```

In general, we get the following payloads: pkt1: [3B, 01, 02, 03, ...], pkt2: [0, 01, 02, 03, ...], pkt3: [3B, 01, 02, 03, ...], ...

*Packet payloads are not random at all!*

**Comment by FMNSSun** [comment]
Fixed in the latest commit.
